export const metadata = {
  title: 'HipHop Communication',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div>navbar</div>
        <h1>
          <a href='/'>Home</a>
          <a href='/board'>Board</a>
        </h1>
        {children}
      </body>
    </html>
  );
}
